# Generated by Django 5.1 on 2024-09-10 08:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chip',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='chip',
            name='date_deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chip',
            name='date_edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chip',
            name='denomination',
            field=models.FloatField(),
        ),
    ]
