# Generated by Django 5.1 on 2024-09-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chip', '0002_chip_date_created_chip_date_deleted_chip_date_edited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chip',
            name='date_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
