# Generated by Django 5.1.1 on 2024-09-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot_machine',
            name='bv_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='slot_machine',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
