# Generated by Django 5.1.1 on 2024-09-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0003_gameday_hall_slotmachine_slotmachinerecord_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='game_days',
        ),
        migrations.AddField(
            model_name='hall',
            name='slot_machines',
            field=models.ManyToManyField(to='slot.slotmachine'),
        ),
    ]
