# Generated by Django 5.1 on 2024-09-11 15:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='denomination',
        ),
        migrations.RemoveField(
            model_name='table',
            name='quantity',
        ),
        migrations.AddField(
            model_name='table',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='table',
            name='flot',
            field=models.JSONField(default=dict),
        ),
    ]
