# Generated by Django 5.1.1 on 2024-09-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_remove_table_denomination_remove_table_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='flot',
            new_name='close_flot',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='created_at',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='table',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='table',
            name='close_flot_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='table',
            name='date_deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='date_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='name',
            field=models.CharField(default='Default Table Name', max_length=200),
        ),
        migrations.AddField(
            model_name='table',
            name='open_flot',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='table',
            name='open_flot_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='table',
            name='result',
            field=models.FloatField(default=0.0),
        ),
    ]
